language: python
python:
  - "3.4"
env:
  matrix:
   - FLASK="Flask<0.11"
branches:
    only:
        - master
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install "$Flask"
  - pip install python-coveralls
  - pip install coverage

after_success:
    - coveralls
