language: python
python:
  - "2.7"
  - "3.5"
branches:
    only:
        - master
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install "$Flask"
  - pip install python-coveralls
  - pip install coverage

after_success:
    - coveralls
